# Generated by Django 2.2.4 on 2021-04-16 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_template_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Super_Villian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=45)),
                ('code_name', models.CharField(max_length=45)),
                ('is_good', models.BooleanField(verbose_name=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='super_villians', to='user_template_app.Team')),
            ],
        ),
    ]
