# Generated by Django 2.2.4 on 2021-04-16 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_template_app', '0002_super_villian'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Super_Villian',
            new_name='Super_Villain',
        ),
    ]
