# Generated by Django 2.2.4 on 2021-04-16 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_template_app', '0003_auto_20210416_1459'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Super',
            new_name='SuperHero',
        ),
    ]
