# Generated by Django 2.2.4 on 2021-04-19 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_template_app', '0005_auto_20210416_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='super_villain',
            name='is_good',
        ),
        migrations.RemoveField(
            model_name='superhero',
            name='is_good',
        ),
    ]
